export {NEXT_PAGE, PREVIOUS_PAGE, FILTER_SORT, FILTER_YEAR};

const NEXT_PAGE = "NEXT_PAGE";
const PREVIOUS_PAGE = "PREVIOUS_PAGE";
const FILTER_SORT = "FILTER_SORT";
const FILTER_YEAR = "FILTER_YEAR";