export {
    NEXT_PAGE,
    PREVIOUS_PAGE,
    RESET_PAGE,
    NUMBER_PAGES,
    FILTER_SORT,
    FILTER_YEAR,
    CHECKBOX_FILTER_GENRE,
    RESET_CHECKBOX_FILTERS
};

const NEXT_PAGE = "NEXT_PAGE";
const PREVIOUS_PAGE = "PREVIOUS_PAGE";
const RESET_PAGE = "RESET_PAGE";
const NUMBER_PAGES = "NUMBER_PAGES";
const FILTER_SORT = "FILTER_SORT";
const FILTER_YEAR = "FILTER_YEAR";
const CHECKBOX_FILTER_GENRE = "CHECKBOX_FILTER_GENRE";
const RESET_CHECKBOX_FILTERS = "RESET_CHECKBOX_FILTERS";
