export {NEXT_PAGE, PREVIOUS_PAGE, RESET_PAGE, NUMBER_PAGES, FILTER_SORT, FILTER_YEAR};

const NEXT_PAGE = "NEXT_PAGE";
const PREVIOUS_PAGE = "PREVIOUS_PAGE";
const RESET_PAGE = "RESET_PAGE";
const NUMBER_PAGES = "NUMBER_PAGES";
const FILTER_SORT = "FILTER_SORT";
const FILTER_YEAR = "FILTER_YEAR";
